version: '3'

networks:
    main:

volumes:
    config_nginx:
        driver: local
    config_muximux:
        driver: local
    config_deluge:
        driver: local
    config_transmission:
        driver: local
    config_sickrage:
        driver: local
    config_couchpotato:
        driver: local
    config_headphones:
        driver: local
    config_sonarr:
        driver: local
    config_explorer:
        driver: local
    config_db:
        driver: local
    config_plex:
        driver: local
    config_openvpn:
        driver: local
    torrents:
        driver: local

services:
    nginx:
        build: images/nginx
        restart: always
        networks:
            - main
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - config_nginx:/config
        env_file:
            - env_config

    muximux:
        # image: linuxserver/muximux
        build:
          context: images/muximux
          dockerfile: Dockerfile
        restart: always
        networks:
            - main
        volumes:
            - config_muximux:/config
        env_file:
            - env_config

    transmission:
        # image: linuxserver/transmission
        build:
          context: images/transmission
          dockerfile: Dockerfile
        restart: always
        networks:
            - main
        ports:
            - "51413:51413"
            - "51413:51413/udp"
        volumes:
            - config_transmission:/config
            - torrents:/downloads
        env_file:
            - env_config

    deluge:
        image: linuxserver/deluge
        # build: images/deluge
        restart: always
        networks:
            - main
        ports:
            - "58846:58846"
            - "58946:58946"
            - "58946:58946/udp"
        volumes:
            - config_deluge:/config
            - torrents:/downloads
        env_file:
            - env_config

    sickrage:
        image: linuxserver/sickrage
        restart: always
        ports:
            - "8081:8081"
        networks:
            - main
        volumes:
            - config_sickrage:/config
            - torrents:/downloads
        env_file:
            - env_config

    couchpotato:
        image: linuxserver/couchpotato
        restart: always
        networks:
            - main
        volumes:
            - config_couchpotato:/config
            - torrents:/downloads
        env_file:
            - env_config

    headphones:
        image: linuxserver/headphones
        restart: always
        networks:
            - main
        volumes:
            - config_headphones:/config
            - torrents:/downloads
        env_file:
            - env_config

    sonarr:
        image: linuxserver/sonarr
        restart: always
        networks:
            - main
        volumes:
            - config_sonarr:/config
            - torrents:/downloads
        env_file:
            - env_config

    explorer:
        build:
          context: images/explorer
          dockerfile: Dockerfile
        restart: always
        networks:
            - main
        volumes:
            - config_explorer:/var/www/html
            - torrents:/var/www/files
        env_file:
            - env_config

    plex:
        image: linuxserver/plex
        restart: always
        networks:
            - main
        ports:
            - "32400:32400"
            - "32400:32400/udp"
            # - "32469:32469"
            # - "32469:32469/udp"
            # - "5353:5353/udp"
            # - "1900:1900/udp"
        volumes:
            - config_plex:/config
            - torrents:/downloads
        env_file:
            - env_config

    openvpn:
        image: kylemanna/openvpn
        restart: always
        networks:
            - main
        ports:
            - "1194:1194/udp"
        volumes:
            - config_openvpn:/etc/openvpn
        env_file:
            - env_config
        cap_add:
            - NET_ADMIN
